apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-database
  namespace: rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-database
  template:
    metadata:
      labels:
        app: devops-database
    spec:
      containers:
        - name: mongodb
          image: 2024dock/devops-database:1.0.0
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mongo-user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mongo-password
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc
