apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: my-app
  namespace: flux-system
resources:
  - deployment.yaml
  - service.yaml
  - image-repo.yaml
  - image-policy.yaml
